# bacon.toml

[jobs.webserver]
command = ["cargo", "run", "--", "--serve"]
need_stdout = true

# critical for servers:
background = true
on_change_strategy = "kill_then_restart" # restart on changes

# optional but usually important so shutdown is graceful:
kill = ["kill", "-s", "INT"]
