[env]
RUST_LOG = "info,sqlx=warn,tower_http=info,eran_codes=debug"
DATABASE_URL = "postgres://app:app@localhost:5432/app"
HOST = "localhost"
PORT = "3002"
SESSION_SECRET = "PLoKvBwqreZjcOyPXids3Zp5cJTAeal3G3SvAPVeSW8Oap40UfBM8U5oNa7tHwwEuQhgq4TkLxyWmwcxeZYkMg"
RUSTC_WRAPPER = ""

[alias]
r = "run"
t = "test"
b = "build"
c = "check"
fmt = "fmt --all"
clippy = "clippy --all-targets --all-features"
with-db = "run --bin with_db --"
